// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryManagmentSystem.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string CustomerN { get; set; }

    public string CustomerP { get; set; }

    public string Adress { get; set; }

    public string ZipCode { get; set; }

    public string PaymentInfo { get; set; }
}