// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryManagmentSystem.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string Category { get; set; }

    public string SubCategory { get; set; }

    public string Brand { get; set; }

    public string SupplierInfo { get; set; }

    public decimal? CostPrice { get; set; }

    public decimal? SellingPrice { get; set; }
}