// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryManagmentSystem.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string SupplierN { get; set; }

    public string Adress { get; set; }

    public decimal? SupplierRating { get; set; }

    public string ContactPerson { get; set; }
}