// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryManagmentSystem.Models;

public partial class Warehouse
{
    public int WarehouseId { get; set; }

    public string Location { get; set; }
}